version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: administrateur
      POSTGRES_DB: WaitingList
    ports:
      - "5431:5431"
    command: [ "postgres", "-p", "5431" ]

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'maleknoura@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_LISTEN_PORT: '5050'
    ports:
      - "5050:5050"
