version: '3'
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: administrateur
      POSTGRES_DB: WaitingList
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
