spring:
  datasource:
    url: jdbc:mysql://localhost:5432/WaitingList
    username: postgres
    password: administrateur
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: prod

logging:
  level:
    root: INFO
