spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WaitingList
    username: postgres
    password: administrateur
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: prod

logging:
  level:
    root: INFO
