spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WaitingList
    username: postgres
    password: administrateur
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev

logging:
  level:
    root: DEBUG
