spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/WaitingList
    username: postgres
    password: administrateur
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Ajoutez cette ligne
    show-sql: true